apiVersion: ai.sap.com/v1alpha1
kind: ServingTemplate
metadata:
  name: sap-pm-bert-pipeline
  annotations:
    scenarios.ai.sap.com/description: "SAP PM BERT Model API"
    scenarios.ai.sap.com/name: "sap-pm-scenario"
    executables.ai.sap.com/description: "Inference executable"
    executables.ai.sap.com/name: "sap-pm-infer"
  labels:
    scenarios.ai.sap.com/id: "sap-pm-scenario"
    ai.sap.com/version: "1.0.0"
spec:
  template:
    apiVersion: "serving.kserve.io/v1beta1"
    metadata:
      annotations: |
        autoscaling.knative.dev/metric: concurrency
        autoscaling.knative.dev/target: 1
        autoscaling.knative.dev/targetBurstCapacity: 0
      labels: |
        ai.sap.com/resourcePlan: starter
    spec: |
      predictor:
        minReplicas: 1
        maxReplicas: 2
        containers:
        - name: kserve-container
          image: docker.io/ahmettahaakturk25/sap-pm-model:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 9000
            protocol: TCP
          command: ["/bin/sh", "-c"]
          args:
            - >
              set -e && echo "Starting SAP PM model server" &&
              gunicorn app:app --timeout 300 --workers 1 --bind 0.0.0.0:9000
